# Generated by Django 5.2.1 on 2025-05-29 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
